//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace mtcmoscow { namespace SensorHub { namespace Temperature {

// Methods
// Readable Properties
public ref class TemperatureGetCelsiusRequestedEventArgs sealed
{
public:
    TemperatureGetCelsiusRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property TemperatureGetCelsiusResult^ Result
    {
        TemperatureGetCelsiusResult^ get() { return m_result; }
        void set(_In_ TemperatureGetCelsiusResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<TemperatureGetCelsiusResult^>^ GetResultAsync(TemperatureGetCelsiusRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<TemperatureGetCelsiusResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<TemperatureGetCelsiusResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    TemperatureGetCelsiusResult^ m_result;
};

public ref class TemperatureGetFahrenheitsRequestedEventArgs sealed
{
public:
    TemperatureGetFahrenheitsRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property TemperatureGetFahrenheitsResult^ Result
    {
        TemperatureGetFahrenheitsResult^ get() { return m_result; }
        void set(_In_ TemperatureGetFahrenheitsResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<TemperatureGetFahrenheitsResult^>^ GetResultAsync(TemperatureGetFahrenheitsRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<TemperatureGetFahrenheitsResult^>
        {
            return t;
        });
    }

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<TemperatureGetFahrenheitsResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    TemperatureGetFahrenheitsResult^ m_result;
};

// Writable Properties
public ref class TemperatureSetCelsiusRequestedEventArgs sealed
{
public:
    TemperatureSetCelsiusRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ double value);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property double Value
    {
        double get() { return m_value; }
    }

    property TemperatureSetCelsiusResult^ Result
    {
        TemperatureSetCelsiusResult^ get() { return m_result; }
        void set(_In_ TemperatureSetCelsiusResult^ value) { m_result = value; }
    }

    static Windows::Foundation::IAsyncOperation<TemperatureSetCelsiusResult^>^ GetResultAsync(TemperatureSetCelsiusRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<TemperatureSetCelsiusResult^>
        {
            return t;
        });
    }

    Windows::Foundation::Deferral^ GetDeferral();

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<TemperatureSetCelsiusResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    double m_value;
    TemperatureSetCelsiusResult^ m_result;
};

public ref class TemperatureSetFahrenheitsRequestedEventArgs sealed
{
public:
    TemperatureSetFahrenheitsRequestedEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ double value);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property double Value
    {
        double get() { return m_value; }
    }

    property TemperatureSetFahrenheitsResult^ Result
    {
        TemperatureSetFahrenheitsResult^ get() { return m_result; }
        void set(_In_ TemperatureSetFahrenheitsResult^ value) { m_result = value; }
    }

    static Windows::Foundation::IAsyncOperation<TemperatureSetFahrenheitsResult^>^ GetResultAsync(TemperatureSetFahrenheitsRequestedEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<TemperatureSetFahrenheitsResult^>
        {
            return t;
        });
    }

    Windows::Foundation::Deferral^ GetDeferral();

private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<TemperatureSetFahrenheitsResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    double m_value;
    TemperatureSetFahrenheitsResult^ m_result;
};

} } } } 
