//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace About {

ref class AboutSignals;

public interface class IAboutSignals
{
    event Windows::Foundation::TypedEventHandler<AboutSignals^, AboutAnnounceReceivedEventArgs^>^ AnnounceReceived;
};

public ref class AboutSignals sealed : [Windows::Foundation::Metadata::Default] IAboutSignals
{
public:
    // Calling this method will send the Announce signal to every member of the session.
    void Announce(_In_ uint16 interfaceMemberVersion, _In_ uint16 interfaceMemberPort, _In_ Windows::Foundation::Collections::IVectorView<AboutObjectDescriptionItem^>^ interfaceMemberObjectDescription, _In_ Windows::Foundation::Collections::IMapView<Platform::String^,Platform::Object^>^ interfaceMemberMetaData);

    // This event fires whenever the Announce signal is sent by another member of the session.
    virtual event Windows::Foundation::TypedEventHandler<AboutSignals^, AboutAnnounceReceivedEventArgs^>^ AnnounceReceived 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AboutSignals^, AboutAnnounceReceivedEventArgs^>^ handler) 
        { 
            return _AnnounceReceived += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AboutSignals^>(sender), safe_cast<AboutAnnounceReceivedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _AnnounceReceived -= token; 
        } 
    internal: 
        void raise(AboutSignals^ sender, AboutAnnounceReceivedEventArgs^ args) 
        { 
            _AnnounceReceived(sender, args);
        } 
    }

internal:
    void Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId);
    void CallAnnounceReceived(_In_ AboutSignals^ sender, _In_ AboutAnnounceReceivedEventArgs^ args);

private:
    alljoyn_busobject m_busObject;
    alljoyn_sessionid m_sessionId;

    virtual event Windows::Foundation::EventHandler<Platform::Object^>^ _AnnounceReceived;

    alljoyn_interfacedescription_member m_memberAnnounce;
};

} } } 
