//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace About {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IAboutService. Instead, AboutServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class AboutServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IAboutService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<AboutServiceEventAdapter^, AboutGetAboutDataCalledEventArgs^>^ GetAboutDataCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AboutServiceEventAdapter^, AboutGetAboutDataCalledEventArgs^>^ handler) 
        { 
            return _GetAboutDataCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AboutServiceEventAdapter^>(sender), safe_cast<AboutGetAboutDataCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetAboutDataCalled -= token; 
        } 
    internal: 
        void raise(AboutServiceEventAdapter^ sender, AboutGetAboutDataCalledEventArgs^ args) 
        { 
            _GetAboutDataCalled(sender, args);
        } 
    }

    event Windows::Foundation::TypedEventHandler<AboutServiceEventAdapter^, AboutGetObjectDescriptionCalledEventArgs^>^ GetObjectDescriptionCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AboutServiceEventAdapter^, AboutGetObjectDescriptionCalledEventArgs^>^ handler) 
        { 
            return _GetObjectDescriptionCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AboutServiceEventAdapter^>(sender), safe_cast<AboutGetObjectDescriptionCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetObjectDescriptionCalled -= token; 
        } 
    internal: 
        void raise(AboutServiceEventAdapter^ sender, AboutGetObjectDescriptionCalledEventArgs^ args) 
        { 
            _GetObjectDescriptionCalled(sender, args);
        } 
    }

    // Property Read Events
    event Windows::Foundation::TypedEventHandler<AboutServiceEventAdapter^, AboutGetVersionRequestedEventArgs^>^ GetVersionRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<AboutServiceEventAdapter^, AboutGetVersionRequestedEventArgs^>^ handler) 
        { 
            return _GetVersionRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<AboutServiceEventAdapter^>(sender), safe_cast<AboutGetVersionRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetVersionRequested -= token; 
        } 
    internal: 
        void raise(AboutServiceEventAdapter^ sender, AboutGetVersionRequestedEventArgs^ args) 
        { 
            _GetVersionRequested(sender, args);
        } 
    }

    // Property Write Events
    // IAboutService Implementation
    virtual Windows::Foundation::IAsyncOperation<AboutGetAboutDataResult^>^ GetAboutDataAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ Platform::String^ interfaceMemberLanguageTag);
    virtual Windows::Foundation::IAsyncOperation<AboutGetObjectDescriptionResult^>^ GetObjectDescriptionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    virtual Windows::Foundation::IAsyncOperation<AboutGetVersionResult^>^ GetVersionAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);


private:
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetAboutDataCalled;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetObjectDescriptionCalled;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetVersionRequested;
};

} } } 
