//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace About {

// Signals
public ref class AboutAnnounceReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property uint16 Version
    {
        uint16 get() { return m_interfaceMemberVersion; }
    internal:
        void set(_In_ uint16 value) { m_interfaceMemberVersion = value; }
    }
    property uint16 Port
    {
        uint16 get() { return m_interfaceMemberPort; }
    internal:
        void set(_In_ uint16 value) { m_interfaceMemberPort = value; }
    }
    property Windows::Foundation::Collections::IVector<AboutObjectDescriptionItem^>^ ObjectDescription
    {
        Windows::Foundation::Collections::IVector<AboutObjectDescriptionItem^>^ get() { return m_interfaceMemberObjectDescription; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IVector<AboutObjectDescriptionItem^>^ value) { m_interfaceMemberObjectDescription = value; }
    }
    property Windows::Foundation::Collections::IMap<Platform::String^,Platform::Object^>^ MetaData
    {
        Windows::Foundation::Collections::IMap<Platform::String^,Platform::Object^>^ get() { return m_interfaceMemberMetaData; }
    internal:
        void set(_In_ Windows::Foundation::Collections::IMap<Platform::String^,Platform::Object^>^ value) { m_interfaceMemberMetaData = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    uint16 m_interfaceMemberVersion;
    uint16 m_interfaceMemberPort;
    Windows::Foundation::Collections::IVector<AboutObjectDescriptionItem^>^ m_interfaceMemberObjectDescription;
    Windows::Foundation::Collections::IMap<Platform::String^,Platform::Object^>^ m_interfaceMemberMetaData;
};


} } } 
